import { expect, test, type WebSocketRoute } from '@playwright/test';

test('local multiplayer menu blocks input while the authority runs and leaves without rejoining', async ({ context }, testInfo) => {
  test.setTimeout(120_000);
  const host = await context.newPage();
  const guest = await context.newPage();
  let guestSocket: WebSocketRoute | undefined;
  let latestRoomMessage = '';
  await guest.routeWebSocket('**/socket.io/**', (socket) => {
    guestSocket = socket;
    const server = socket.connectToServer();
    server.onMessage((message) => {
      if (String(message).startsWith('42[\"room-state\"')) latestRoomMessage = String(message);
      socket.send(message);
    });
  });
  const errors: string[] = [];
  host.on('pageerror', (error) => errors.push(error.message));
  guest.on('pageerror', (error) => errors.push(error.message));
  const inputs: Array<{ moveX: number; moveZ: number; action: boolean }> = [];
  guest.on('websocket', (socket) => socket.on('framesent', ({ payload }) => {
    const text = String(payload);
    if (!text.startsWith('42[')) return;
    const [event, frame] = JSON.parse(text.slice(2));
    if (event === 'input-frame') inputs.push(frame);
  }));
  await Promise.all([host.goto('/'), guest.goto('/')]);
  await host.getByTestId('create-room').click();
  await expect(host.getByTestId('room-code')).not.toHaveText('——');
  await guest.getByTestId('room-code-input').fill((await host.getByTestId('room-code').innerText()).trim());
  await guest.getByTestId('join-room').click();
  await expect(host.getByTestId('roster').locator('li')).toHaveCount(2);
  await host.locator('#lobby-role-picker [data-role-choice="ghost"]').click();
  await guest.locator('#lobby-role-picker [data-role-choice="child"]').click();
  await host.getByTestId('start-match').click();
  await expect(guest.locator('#multiplayer-menu-button')).toBeVisible({ timeout: 45_000 });
  await expect.poll(() => guest.evaluate(() => window.__THREE_GAME_DIAGNOSTICS__?.viewerFrame?.phase)).toBe('playing');
  await guest.keyboard.down('d');
  await expect.poll(() => inputs.some((frame) => frame.moveX > 0)).toBe(true);
  await guest.keyboard.press('Escape');
  const menu = guest.locator('#multiplayer-menu');
  await expect(menu).toBeVisible();
  await expect(menu).toContainText('联机对局仍在进行');
  await guest.keyboard.up('d');
  await expect.poll(() => inputs.at(-1)?.moveX).toBe(0);
  inputs.length = 0;
  const timer = await host.locator('#match-timer').innerText();
  await guest.keyboard.down('w');
  await expect(host.locator('#match-timer')).not.toHaveText(timer);
  await expect.poll(() => inputs.length).toBeGreaterThan(5);
  expect(inputs.every((frame) => frame.moveX === 0 && frame.moveZ === 0 && !frame.action)).toBe(true);
  await guest.keyboard.up('w');
  await guest.locator('#multiplayer-help summary').click();
  await expect(menu).toContainText('鼠标左键');
  await guest.locator('#multiplayer-sound').click();
  await expect(guest.locator('#audio-toggle')).toHaveText('声音：关');
  await guest.screenshot({ path: testInfo.outputPath('multiplayer-menu-desktop.png') });
  await guest.setViewportSize({ width: 390, height: 844 });
  await guest.screenshot({ path: testInfo.outputPath('multiplayer-menu-portrait.png') });
  await guest.setViewportSize({ width: 844, height: 390 });
  await guest.screenshot({ path: testInfo.outputPath('multiplayer-menu-landscape.png') });
  const bounds = await menu.boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.height).toBeLessThanOrEqual(390);
  await guest.locator('#multiplayer-leave').click();
  await expect(guest.locator('#multiplayer-confirm')).toBeVisible();
  await guest.keyboard.press('Escape');
  await expect(guest.locator('#multiplayer-confirm')).toBeHidden();
  await expect(menu).toBeVisible();
  await guest.keyboard.press('Escape');
  await expect(menu).toBeHidden();
  await guest.evaluate(() => window.dispatchEvent(new Event('blur')));
  await expect(menu).toBeHidden();
  await guest.locator('#multiplayer-menu-button').click();
  // Deliver an end-of-match room state through the transport while the menu is open.
  const endedMessage = JSON.parse(latestRoomMessage.slice(2));
  endedMessage[1].phase = 'ended';
  guestSocket!.send(`42${JSON.stringify(endedMessage)}`);
  await expect(menu).toBeHidden();
  await expect(guest.locator('#result-overlay')).toBeVisible();
  guestSocket!.send(latestRoomMessage);
  await expect(guest.locator('#result-overlay')).toBeHidden();
  await guest.locator('#multiplayer-menu-button').click();
  guestSocket!.close();
  await expect(menu).toBeHidden();
  await expect(guest.locator('#multiplayer-menu-button')).toBeVisible({ timeout: 15_000 });
  await host.locator('#multiplayer-menu-button').click();
  await host.locator('#multiplayer-leave').click();
  await host.locator('#multiplayer-confirm-leave').click();
  await expect(host.getByTestId('lobby-panel')).toBeVisible();
  expect(await host.evaluate(() => sessionStorage.getItem('i-am-a-ghost:room-session'))).toBeNull();
  await expect.poll(() => guest.evaluate(() => {
    const session = JSON.parse(sessionStorage.getItem('i-am-a-ghost:room-session') ?? '{}');
    return session.session?.isHost;
  })).toBe(true);
  await guest.locator('#multiplayer-menu-button').click();
  await guest.locator('#multiplayer-leave').click();
  await guest.locator('#multiplayer-confirm-leave').click();
  await expect(guest.getByTestId('lobby-panel')).toBeVisible();
  await guest.reload();
  await expect(guest.getByTestId('create-room')).toBeVisible();
  await expect(guest.locator('#audio-toggle')).toHaveText('声音：关');
  expect(await guest.evaluate(() => sessionStorage.getItem('i-am-a-ghost:room-session'))).toBeNull();
  expect(errors).toEqual([]);
});
